name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3

      - name: Build Site
        run: |
          echo "--- Preparing build directory ---"
          mkdir build
          rsync -av --progress . ./build --exclude ".git" --exclude ".github" --exclude "build" --exclude ".gitignore" --exclude ".cp-images"
          
          echo "--- Disabling Jekyll ---"
          touch ./build/.nojekyll

          echo "--- Creating config.js ---"
          mkdir -p ./build/cripto_moeda/js
          echo "const COINGECKO_API_KEY = '${{ secrets.COINGECKO_API_KEY }}';" > ./build/cripto_moeda/js/config.js
          
          echo "--- Verifying build directory contents ---"
          ls -lRa build

      - name: Deploy to gh-pages
        run: |
          cd build
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy"
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:gh-pages
